### ISSUE TITLE
Support attachments in chat_post_message

### ISSUE THREAD

**Issue by jerith** [Leonidas-from-XIV/slacko#11]
Slack messages can have attachments, as documented at https://api.slack.com/docs/message-attachments.

Adding attachment support would probably involve creating a new `attachment` type and adding an optional parameter of type `attachment list` to `Slacko.chat_post_message`.

**Comment by jerith** [comment]
I have a somewhat hacky attempt at an implementation over here: https://github.com/jerith/slacko/compare/ocaml-4.03...post-attachment

I builds on top of #12, so it doesn't make much sense to open a pull request before that is resolved. :-)

**Comment by Leonidas-from-XIV** [comment]
Yep, let's get #12 merged first, otherwise GitHub won't even let me write any review comments on this.

**Comment by jerith** [comment]
Fixed in #13.
