### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by yallop** [Leonidas-from-XIV/slacko#16]
The latest release in opam-repository is `0.12.0`, which has a much less precisely-typed API than `master`.  It'd be convenient to have a more recent version available via opam.

**Comment by Leonidas-from-XIV** [comment]
I completely agree, considering `0.12.0` was ages ago. I would like to make a new release soon, but there are blocking issues like #10 which I would like to address first. To make sure we find all the other potential problems, we have #14 which will allow us to ship a release where we can see that it should work fine.

**Comment by Leonidas-from-XIV** [comment]
I released `0.13.0` with the newer API, which was merged to opam-repository today.

I guess having a not-yet-perfect API and iterate faster is better than having no new release for years and a completely different API in the repo. Feel free to report any issues with the new release, I will try to do any incremental fixes quickly.

**Comment by yallop** [comment]
Thanks!
