### ISSUE TITLE
Integer overflow with certain responses on 32-bit platforms

### ISSUE THREAD

**Issue by eras** [Leonidas-from-XIV/slacko#2]
In particular, chat_send_message caused issues for me, on Raspberry Pi.

This would be resolved by refraining to use Yojson.Basic-module that does integer conversions always, whereas Yojson.Safe uses Intlit in case of integer overflow.

**Comment by Leonidas-from-XIV** [comment]
Thanks for reporting, that's an excellent point! I was only using `Yojson.Basic.json` for the convenient accessor functions from `Yojson.Basic.Util`, so I rolled my own `Safe.Util` now. I'll probably eventually refactor it to avoid exceptions, but for now it should be enough to solve your issue.

Can you please test 77879f9 and check if it solves your issue?

**Comment by eras** [comment]
Doesn't seem to work, though. In fact, now it's broken for 64-bit as well :-).

    % _build/src/slack_notify.native -u matomatikki -t xoxb.. '#channel' testing
    Your token is xoxb.. , the channel is #channel and the message is 'testing'.
    slack-notify: internal error, uncaught exception:
                  Slacko.Lookup_failed

**Comment by Leonidas-from-XIV** [comment]
The error is a different thing now, it can't parse the JSON from Slack. I've tried adjusting it, but I've seem to have hit an issue with ppx_deriving_yojson: https://github.com/whitequark/ppx_deriving_yojson/issues/28. Let's see how this unfolds.

**Comment by Leonidas-from-XIV** [comment]
I believe this should be fixed now, this time I even ran the code :-). I've reworked the previous fix as well.
