### ISSUE TITLE
online docs is a 404

### ISSUE THREAD

**Issue by c-cube** [Leonidas-from-XIV/slacko#38]

**Comment by Leonidas-from-XIV** [comment]
I'll look into this. `dune-release` has pushed to `gh-pages` and the settings say everything is fine. But it looks like the docs that were generated are missing bits.

**Comment by c-cube** [comment]
With such tools, it's "trust, but verify" in my experience :)
I think dune-release might push docs in a subdirectory.

**Comment by Leonidas-from-XIV** [comment]
I think my problem was that everything was just very old so I upgraded all the dependencies and pushed again. Voila, [docs are back](https://leonidas-from-xiv.github.io/slacko/)!
