### ISSUE TITLE
opam: Does not deliver setup.ml nor does it have running oasis in opam build rules

### ISSUE THREAD

**Issue by eras** [Leonidas-from-XIV/slacko#6]
This results in opam pinned instance of slacko not building, because setup.ml does not exist.

Suggested fix: add oasis the the opam build rules and as a dependency to the package.

**Comment by Leonidas-from-XIV** [comment]
The reason why the `opam` file does not specify `oasis` is due the fact that I'd like to keep the releases oasis-free, since it only generates a `setup.ml` and has otherwise a long tail of dependencies.

There is no way to specify "development" dependencies, as with NPM, is there?
